config/routes.rb
Rails.application.routes.draw do
  resources :products do
      put :update, to: 'products#update', as: :update
    collection do
      get :platos_principales
      get :entradas
      get :postres
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations'  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'home#index'

  get "/contacto", to: 'home#contacto'

  resources :users do
    resources :addresses
    resources :carritos do
      get '/agregar_item', to: 'carritos#agregar_item', as: 'agregar_item'
      get '/quitar_item', to: 'carritos#quitar_item', as: 'quitar_item'
    end
  end

end

app/models/carrito.rb
class Carrito < ApplicationRecord
    validates :user, presence: true

    belongs_to :user, foreign_key: "user_id"
    belongs_to :address, foreign_key: "address_id", optional: true
    has_many :item_carrito, foreign_key: "carrito_id"

    def items
        ItemCarrito.where(carrito_id: id).all
    end

    def agregar_producto product_id
        ItemCarrito.create(carrito: self, product_id: product_id)
        self.total_cost += Product.find(product_id).price
        self.save
    end
end

app/controllers/carritos_controller.rb
class CarritosController < ApplicationController
    def index
        if user_signed_in? && current_user.id == params[:user_id].to_i
            @carrito = current_user.carrito_compras
            @items = ItemCarrito.joins(:product).where(carrito_id: @carrito.id).select(:product_id).distinct.order(:name)
        else
            flash[:error] = "Debes iniciar sesión."
            redirect_to products_path   
        end
    end

    def agregar_item
        if user_signed_in? && current_user.id == params[:user_id].to_i
            @carrito = current_user.carrito_compras
            @carrito.agregar_producto(params[:product_id])
            flash[:success] = "Se agrego el producto con exito."
        else
            flash[:error] = "No se pudo agregar el producto."
        end
        redirect_back(fallback_location: products_path)
    end

    def quitar_item
        if user_signed_in? && current_user.id == params[:user_id].to_i
            @carrito = current_user.carrito_compras
            item = ItemCarrito.where(carrito_id: @carrito.id, product_id: params[:product_id]).first
            price = Product.find(params[:product_id]).price
            if item.destroy
                @carrito.total_cost -= price
                @carrito.save
            end
        end
        redirect_back(fallback_location: products_path)
    end
end

app/helpers/carritos_helper.rb
module CarritosHelper
end

app/views/carritos/index.html.erb
<div class="container">
  <h1 class="display-3 mb-3 mt-4">Mi Carrito</h1>
  <% if !@items.empty?%>
    <div class="row">
      <div class="col-md-6">
        <% @items.each do |item| %>
          <div class="card mb-3" style="max-width: 540px;">
            <div class="row g-0">
              <div class="col-4">
                <img src= <%= item.product.photo_url%> class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-8">
                <div class="card-body">
                  <h5 class="card-title"> <%= item.product.name %></h5>
                  <p> <%= "Total: #{number_to_currency(@carrito.items.where(product_id: item.product_id).count * item.product.price, :unit => "CLP", precision: 0)}"%> </p>

                  <span> <%= "Cantidad: #{@carrito.items.where(product_id: item.product_id).count}" %> </span>
                  <div class="float-end">
                    <%= link_to user_carrito_quitar_item_path(carrito_id: current_user.carrito_compras.id, user_id: current_user.id, product_id: item.product.id),
                    class: 'btn btn-sm btn-secondary' do%>
                      <%= fa_icon("minus")%>
                    <% end %>
                    <%= link_to user_carrito_agregar_item_path(carrito_id: current_user.carrito_compras.id, user_id: current_user.id, product_id: item.product.id),
                    class: 'btn btn-sm btn-secondary' do%>
                      <%= fa_icon("plus")%>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <div class="col-md-6 float-start">
        <div class="card mb-3" style="max-width: 540px;">
          <div class="card-body">
            <div class="row align-items-center">
              <div class="col-6">
                <b class="card-title h4">Costo Total:</b>
              </div>

              <div class="col-6">
                <span class="float-end h6 me-2"><%= number_to_currency(@carrito.total_cost, :unit => "CLP", precision: 0) %></span><br/>
              </div>
              
              <div class="col-12">
                <div class="btn btn-lg btn-primary float-end mt-3 w-100"> Hacer Pedido </div>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  <% else %>
    <span class="display-6"> No tienes nada en tu carrito </span>
    <%= fa_icon('frown-o 2x')%>
  <% end %>
</div>