config/routes.rb
Rails.application.routes.draw do
  resources :products do
      put :update, to: 'products#update', as: :update
    collection do
      get :platos_principales
      get :entradas
      get :postres
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations'  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'home#index'

  get "/contacto", to: 'home#contacto'

  resources :users do
    resources :addresses
    resources :carritos do
      get '/agregar_item', to: 'carritos#agregar_item', as: 'agregar_item'
      get '/quitar_item', to: 'carritos#quitar_item', as: 'quitar_item'
    end
  end

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def index
    if user_signed_in? && current_user.id == params[:user_id].to_i
      @addresses = Address.where(user_id: current_user.id)
    else
      flash[:error] = "Debes haber iniciado sesión"
      redirect_to products_path
    end
  end

  def new
    @address = Address.new(create_params)
    @address.user_id = current_user.id
    if @address.save
      flash[:success] = "Dirección añadida con exito."
    else
      flash[:error] = "No se pudo añadir la dirección, porfavor intente denuevo."
    end
    redirect_to user_addresses_path(current_user.id)
  end

  def edit
    if user_signed_in? && current_user.id == params[:user_id].to_i
      @address = Address.find(params[:id])
      if @address.update(create_params)
        flash[:success] = "Se ha actualizado con exito la dirección."
      else
        flash[:error] = "No se pudo actualizar la dirección, porfavor intente denuevo."
      end
      redirect_to user_addresses_path(current_user.id)
    else
      flash[:error] = "Debes haber iniciado sesión"
      redirect_to products_path
    end
  end
  def destroy
    if user_signed_in? && current_user.id == params[:user_id].to_i
      @address = Address.find(params[:id])
      if @address.destroy
        flash[:success] = "Se ha eliminado con exito la dirección."
      else
        flash[:error] = "No se pudo eliminar la dirección, porfavor intente denuevo."
      end
      redirect_to user_addresses_path(current_user.id)
    else
      flash[:error] = "Debes haber iniciado sesión"
      redirect_to products_path
    end
  end

  private

  def create_params
    params.require(:address).permit(:direccion, :comuna, :oficina, :user_id)
  end


end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_edit.html.erb
<div class="modal-header background-color3 ">
  <h4 class="modal-title" id="myModalLabel">Editar Dirección</h4>
</div>
<%= form_for :address, url: edit_user_address_path(id: address.id, user_id: current_user.id), method: :get do |f| %>
  <div class="modal-body background-color2">
    <div class="row">
        <div class="col-8 mt-3">
        <%= f.label :direccion, class: "form-label" %><br>
        <%= f.text_field :direccion, class: "form-control", value: address.direccion %>
        </div>

        <div class=" col-4 mt-3">
            <%= f.label :oficina, class: "form-label" %><br>
            <%= f.text_field :oficina, class: "form-control", value: address.oficina %>
        </div>
        
        <div class="col mt-3">
        <%= f.label :comuna, class: "form-label" %><br>
        <%= f.select :comuna, ['Providencia', 'La Reina', 'Las Condes', 'Vitacura', 'Ñuñoa'], {}, class: "form-select", value: address.comuna %>
        </div>
    </div>
  </div>
  <div class="modal-footer background-color3">
    <%= f.submit "Editar Dirección", class: "btn btn-warning float-end" %>
  </div>
<% end %>

app/views/addresses/_new.html.erb
<%= form_for :address, url: new_user_address_path(current_user.id), method: :get do |f| %>
    <div class="row">
        <div class="col-8 mt-3">
        <%= f.label :direccion, class: "form-label" %><br>
        <%= f.text_field :direccion, class: "form-control" %>
        </div>

        <div class=" col-4 mt-3">
            <%= f.label :oficina, class: "form-label" %><br>
            <%= f.text_field :oficina, class: "form-control" %>
        </div>
        

        <div class="col mt-3">
        <%= f.label :comuna, class: "form-label" %><br>
        <%= f.select :comuna, ['Las Condes', 'La Reina', 'Providencia', 'Vitacura', 'Ñuñoa'], {}, class: "form-select" %>
        </div>
        
        <div class="mt-3">
            <%= f.submit "Añadir Dirección", class: "btn btn-warning float-end" %>
        </div>
    </div>

<% end %>

app/views/addresses/index.html.erb
<div class="container">
<div class="container">
    <h2 class="mt-3", style="color: green"> <%= flash[:success] %> </h2>
    <h2 class="mt-3" style="color: red"> <%= flash[:error] %> </h2>
</div>
  <h1 class="display-3 mb-3 mt-4">Mis Direcciones</h1>
  <% if !@addresses.empty?%>
    <table class="table table-bordered border border-dark background-color">
      <thead>
        <tr>
          <th scope="col" class="h6" >Dirección</th>
          <th scope="col" class="h6">Oficina/Dpto</th>
          <th scope="col" class="h6">Comuna</th>
          <th scope="col" class="h6"> <span class="d-flex justify-content-center"><%= fa_icon(:gear) %></span></th>
        </tr>
      </thead>
      <tbody>
      <% @addresses.each do |address| %>
        <tr>
          <td class="h6 align-middle"> <%= address.direccion %> </th>
          <td class="h6 align-middle"> <%= address.oficina %> </td>
          <td class="h6 align-middle"> <%= t(address.comuna) %> </td>
          <td class="d-flex align-middle  justify-content-center border-0">  
            <%= button_to user_address_path(id: address.id), method: :delete, class: "border-0 ms-0 me-2" do %>
              <span class="btn btn-danger border-0"> <%= fa_icon('trash')%></span> 
            <% end %>
            
            <%= link_to edit_user_address_path(id: address.id, user_id: current_user.id),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => "#modal-edit-#{address.id}"} do  %>
              <span class="btn btn-secondary" ><%= fa_icon('pencil') %> </span>
            <% end %>
            <div id="modal-edit-<%= address.id %>" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <%= render 'addresses/edit', address: address %>
                </div>
              </div>
            </div>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% end %>

  <div class="card background-color3" style="width: 100%;">
    <div class="card-body">
      <h4 class="display-6">Añadir Dirección</h4>
      <%= render 'addresses/new' %>
    </div>
  </div>
</div>