config/routes.rb
Rails.application.routes.draw do
  resources :products do
      put :update, to: 'products#update', as: :update
    collection do
      get :platos_principales
      get :entradas
      get :postres
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations'  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'home#index'

  get "/contacto", to: 'home#contacto'

  resources :users do
    resources :addresses
    resources :carritos do
      get '/agregar_item', to: 'carritos#agregar_item', as: 'agregar_item'
      get '/quitar_item', to: 'carritos#quitar_item', as: 'quitar_item'
    end
  end

end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :category, presence: true
  validates :price, presence: true
  validates :description, presence: true

  enum category: {
    entrada: "Entrada",
    plato_principal: "Plato Principal",
    postre: "Postre",
  }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def create
    @product = Product.new(create_params)
    if @product.save
      flash[:success] = "Producto creado con exito."
    else
      flash[:error] = "No se pudo crear el producto, porfavor intente denuevo."
    end
    redirect_to products_path
  end

  def update
    @product = Product.find(params[:product_id])
    @product.update(create_params)

    if @product.save
      flash[:success] = "Producto actualizado con exito"
      redirect_to products_path
    else
      flash[:error] = "No se pudo actualizar el producto, porfavor intente denuevo."
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      flash[:success] = "Producto eliminado con exito."
    else
      flash[:error] = "No se pudo crear el producto, porfavor intente denuevo."
    end
    redirect_to products_path
  end

  def entradas
    @products = Product.where(category: "Entrada")
  end

  def platos_principales
    @products = Product.where(category: "Plato Principal")
  end

  def postres
    @products = Product.where(category: "Postre")
  end

  private
  def create_params
    params.require(:product).permit(:name, :category, :price, :description, :photo_url)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_cards.html.erb
  <div class="container">
    <div class="row mb-3">
      <div class="col">
        <span class="display-3 mt-4"> <%= title %> </span>
      </div>

      <div class="col">
        <% if user_signed_in? && current_user.is_admin?%>
          <%= link_to 'Añadir Producto', new_product_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-warning btn-lg float-end'}  %>
          <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
              <div class="modal-content">
                <%= render "products/new" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

<div class="container-fluid">
  <div class="row justify-content-start">
    <% @products.each do |product|%>
    <div class="col-sm-12 col-md-6 col-lg-4 col-xl-3">
        <div class="card mb-4 me-4" style="width: 100%; height: 90%">
            <img src=<%=product.photo_url%> class="card-img-top" product.name%>
            <div class="card-body">
              <h5 class="card-title"><%= product.name%></h5>
              <p class="card-text"><%= product.description%></p>
              <div class="botones mt-5">
                <% if user_signed_in? %>
                  <% if current_user.is_admin? %>
                    <%= button_to product_path(product.id), method: :delete, class: "btn btn-danger float-start boton-eliminar" do %> 
                      <%= fa_icon('trash') %>
                    <% end %>
                    <%= link_to product_update_path(product.id),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => "#modal-edit-#{product.id}", class: 'btn btn-secondary boton-editar'} do  %>
                      <%= fa_icon('pencil')%>
                    <% end %>
                    <div id="modal-edit-<%= product.id %>" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <%= render "products/edit", product: product %>
                        </div>
                      </div>
                    </div>
                  <% end %>
                  <%= link_to user_carrito_agregar_item_path(carrito_id: current_user.carrito_compras.id, user_id: current_user.id, product_id: product.id),
                   class: "btn btn-primary boton-agregar" do%>
                    <%= fa_icon("plus")%>
                  <% end %>
                <% end %>
                <a  class="btn btn-success float-end boton-precio ms-3"><%= number_to_currency(product.price, :unit => "CLP", precision: 0)%></a>
              </div>
            </div>
        </div>
    </div>
    <% end %>
  </div>
</div>

app/views/products/_category_navbar.html.erb
<div class="background-color4">
  <div class="container">
    <div class="h-100 row align-items-center background-color4">
      <div class="col-4">
        <h4 class="product-category"> <%= link_to "Entradas", entradas_products_path, class: "product-text" %></h4>
      </div>
      <div class="col-4">
        <h4 class="product-category"> <%= link_to "Platos Principales", platos_principales_products_path, class: "product-text" %></h4>
      </div>
      <div class="col-4">
        <h4 class="product-category"> <%= link_to "Postres", postres_products_path, class: "product-text" %></h4>
      </div>
    </div>
  </div>
</div>

app/views/products/_edit.html.erb
<div class="modal-header background-color3 ">
  <h4 class="modal-title" id="myModalLabel">Editar Producto</h4>
</div>
<%= form_for product, url: product_update_path(product.id), :method => :put  do |f|%>
  <div class="modal-body background-color2">
    <div>
      <%= f.label :name, Product.human_attribute_name(:name), class: "form-label" %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <br/>
    <div>
      <p class="form-label"> <%= Product.human_attribute_name(:category) %> </p>&nbsp;
      <%= f.radio_button :category, 'Entrada'%>
      <%= f.label :category, "Entrada", :value => 'Entrada', class: "h6"%><br/>&nbsp;
      <%= f.radio_button :category, 'Plato Principal'%>
      <%= f.label :category, "Plato Principal", :value => 'Plato Principal', class: "h6"%><br/>&nbsp;
      <%= f.radio_button :category, 'Postre'%>
      <%= f.label :category, "Postre", :value => 'Postre', class: "h6"%>
    </div>
    <br/>
    <div>
      <%= f.label :description, Product.human_attribute_name(:description), class: "form-label" %><br>
      <%= f.text_area :description, class: "form-control", rows: 3, cols: 40 %>
    </div>

    <div>
      <%= f.label :price, Product.human_attribute_name(:price), class: "form-label" %><br>
      <%= f.number_field :price, class: "form-control" %>
    </div>

    <div>
      <%= f.label :photo_url, Product.human_attribute_name(:photo_url), class: "form-label" %><br>
      <%= f.text_field :photo_url, class: "form-control" %>
    </div>

  </div>

  <div class="modal-footer background-color3">
    <%= f.submit "Editar Producto", class: "btn btn-warning" %>
  </div>
<% end %>

app/views/products/_error_messages.html.erb
<% if @product.errors.any? %>
  <div id="error_explanation" class="mb-4">
    <h3 class="mb-3">
      <%= I18n.t("errors.messages.not_saved",
                 count: @product.errors.count,
                 resource: @product.class.model_name.human.downcase)
       %>
    </h3>
    <ul class="list-group">
      <% @product.errors.full_messages.each do |message| %>
        <li class="list-group-item list-group-item-danger"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/products/_new.html.erb
<div class="modal-header background-color3 ">
  <h4 class="modal-title" id="myModalLabel">Añadir Producto</h4>
</div>
<%= form_for :product, url: products_path  do |f|%>
  <div class="modal-body background-color2">
    <div>
      <%= f.label :name, Product.human_attribute_name(:name), class: "form-label" %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <br/>
    <div>
      <p class="form-label"> <%= Product.human_attribute_name(:category) %> </p>&nbsp;
      <%= f.radio_button :category, 'Entrada'%>
      <%= f.label :category, "Entrada", :value => 'Entrada', class: "h6"%><br/>&nbsp;
      <%= f.radio_button :category, 'Plato Principal'%>
      <%= f.label :category, "Plato Principal", :value => 'Plato Principal', class: "h6"%><br/>&nbsp;
      <%= f.radio_button :category, 'Postre'%>
      <%= f.label :category, "Postre", :value => 'Postre', class: "h6"%>
    </div>
    <br/>
    <div>
      <%= f.label :description, Product.human_attribute_name(:description), class: "form-label" %><br>
      <%= f.text_area :description, class: "form-control", rows: 3, cols: 40 %>
    </div>

    <div>
      <%= f.label :price, Product.human_attribute_name(:price), class: "form-label" %><br>
      <%= f.number_field :price, class: "form-control" %>
    </div>

    <div>
      <%= f.label :photo_url, Product.human_attribute_name(:photo_url), class: "form-label" %><br>
      <%= f.text_field :photo_url, class: "form-control" %>
    </div>

  </div>

  <div class="modal-footer background-color3">
    <%= f.submit "Añadir Producto", class: "btn btn-warning" %>
  </div>
<% end %>

app/views/products/entradas.html.erb
<%= render 'products/category_navbar'%>
<div class="container">
    <h2 class="mt-3", style="color: green"> <%= flash[:success] %> </h2>
    <h2 class="mt-3" style="color: red"> <%= flash[:error] %> </h2>
</div>
<div class="container-fluid">
    <%= render 'products/cards', title: "Entradas" %>
</div>

app/views/products/index.html.erb
<%= render 'products/category_navbar'%>
<div class="container">
    <h2 class="mt-3", style="color: green"> <%= flash[:success] %> </h2>
    <h2 class="mt-3" style="color: red"> <%= flash[:error] %> </h2>
</div>
<div class="container-fluid">
    <%= render 'products/cards', title: "Productos" %>
</div>

app/views/products/platos_principales.html.erb
<%= render 'products/category_navbar'%>
<div class="container">
    <h2 class="mt-3", style="color: green"> <%= flash[:success] %> </h2>
    <h2 class="mt-3" style="color: red"> <%= flash[:error] %> </h2>
</div>
<div class="container-fluid">
    <%= render 'products/cards', title: "Platos Principales" %>
</div>

app/views/products/postres.html.erb
<%= render 'products/category_navbar'%>
<div class="container">
    <h2 class="mt-3", style="color: green"> <%= flash[:success] %> </h2>
    <h2 class="mt-3" style="color: red"> <%= flash[:error] %> </h2>
</div>
<div class="container-fluid">
    <%= render 'products/cards', title: "Postres" %>
</div>