config/routes.rb
Rails.application.routes.draw do
  resources :products do
      put :update, to: 'products#update', as: :update
    collection do
      get :platos_principales
      get :entradas
      get :postres
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations'  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'home#index'

  get "/contacto", to: 'home#contacto'

  resources :users do
    resources :addresses
    resources :carritos do
      get '/agregar_item', to: 'carritos#agregar_item', as: 'agregar_item'
      get '/quitar_item', to: 'carritos#quitar_item', as: 'quitar_item'
    end
  end

end

app/views/layouts/_footer.html.erb
  <div>
    <footer class="footer">
      <div class="container d-flex justify-content-center">

      </div>

      <!-- Copyright -->
      <div class="text-center">
        © 2020 Copyright:
      </div>
      <!-- Copyright -->
    </footer>
  </div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light navbar-custom background-color3">
  <div class= 'container'>
    <a class="navbar-brand" href="#"><%= image_tag("chef-hat.png", height: 50) %></a>
    <div class= navbar-brand>
      <h2> <%= link_to "FoodLovers", root_path, class:"navbar-brand-name" %> </h2>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"> </span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Productos", products_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contacto", contacto_path, class: "nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav ms-auto me-2">
        <li class="nav-item">
          <% if user_signed_in? %>
            <%= link_to user_carritos_path(current_user.id), class: "btn" do%>
              <%= fa_icon('shopping-cart lg') %>
            <% end %>
          <% else %>
            <% flash[:error] = "Debes iniciar sesión." %>
            <%= link_to products_path, class: "btn" do%>
              <%= fa_icon('shopping-cart lg') %>
            <% end %>
          <% end %>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= fa_icon('user-circle lg') %> <%= user_signed_in? ? current_user.name :  "Mi Cuenta" %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>
            <%= link_to "Cerrar Sesión", destroy_user_session_path, :method => :delete, class: "dropdown-item" %>
            <%= link_to "Editar Perfil", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Mis Direcciones", user_addresses_path(current_user.id), class: "dropdown-item" %>

          <% else %>
            <%= link_to "Registrarse", new_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Iniciar Sesión", new_user_session_path, class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProyectoComida</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>

  <body class = 'background-color2'>
    <%= render 'layouts/navbar' %>

    <%= yield %>
  </body>
</html>